name: Fetch zotero bibliography
on:
  schedule:
    - cron: "*/45 9-23 * * *"
    - cron: "0 0-9 * * *"
  push:
    branches:
      - main

jobs:
  fetch_zotero_bibliography:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g zotero-fetch-cli@v1.1.0
      - run: |
          zotero-fetch bibliography --format bibtex "${{ github.workspace }}/jblewandowski-lib.bib"
          zotero-fetch bibliography --format json "${{ github.workspace }}/jblewandowski-lib.zotero.json"
        env:
          ZOTERO_USERID: "8674355"
          ZOTERO_APIKEY: "${{ secrets.ZOTERO_APIKEY }}"
      - run: ls -a
      - run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'fetch-zotero.yml (JB Lewandowski)'
            git config --global user.email 'jblew@users.noreply.github.com'
            git add jblewandowski-lib.bib jblewandowski-lib.zotero.json
            git commit -m "sync: bibliography"
            git push origin main
          else
            echo "No changes"
          fi
